---
name: qBittorrent
version: dev
slug: qbittorrent
description: qBittorrent client for Home Assistant
url: https://github.com/hassio-addons/addon-qbittorrent/tree/main/README.md
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:8080]
init: false
arch:
  - aarch64
  - amd64
  - armv7
map:
  - addon_config:rw
  - share:rw
  - media:rw
ports:
  8080/tcp: 8080
  6881/tcp: 6881
  6881/udp: 6881
