---
name: qBittorrent
version: dev
slug: qbittorrent
description: Free and reliable BitTorrent client with an advanced Web UI
url: https://github.com/jc21/ha_addons/tree/main/qbittorrent
webui: http://[HOST]:[PORT:8080]
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 8080
panel_icon: mdi:download
panel_title: qBittorrent
ports:
  8080/tcp: 8080
  6881/tcp: 6881
  6881/udp: 6881
map:
  - config:rw
  - share:rw
  - media:rw
host_network: false
apparmor: false
privileged:
  - NET_ADMIN
