---
name: n8n
version: dev
slug: n8n
description: Workflow automation for technical people with a visual editor
url: https://github.com/jc21/ha_addons/tree/main/n8n
webui: http://[HOST]:[PORT:5678]
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 5678
panel_icon: mdi:graph-outline
panel_title: n8n
ports:
  5678/tcp: 5678
map:
  - config:rw
  - share:rw
  - media:rw
host_network: false
apparmor: false
environment:
  N8N_HOST: "0.0.0.0"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "http"
  WEBHOOK_URL: "http://localhost:5678/"
  GENERIC_TIMEZONE: "UTC"
options:
  timezone: "UTC"
  webhook_url: ""
  encryption_key: ""
schema:
  timezone: str
  webhook_url: str?
  encryption_key: str?
