name: "HAOS Kiosk Display"
description: >
  Start X server and browser on local HAOS server and display dashboards in kiosk mode (Jeff Kosowsky)
version: "0.9.8"
slug: "haoskiosk"

arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

startup: application
host_network: true
init: false
ingress: true

devices:
  - /dev/fb0
  - /dev/fb1
  - /dev/dri
  - /dev/input/event0
  - /dev/input/event1
  - /dev/input/event2
  - /dev/input/event3
  - /dev/input/mice
  - /dev/input/mouse0
  - /dev/input/mouse1
  - /dev/tty0
  - /dev/tty1
  - /dev/tty7
  - /dev/vc-mem
  - /dev/vchiq
  - /dev/vcsm-cma

privileged:
  - SYS_ADMIN

options:
  ha_username: ""
  ha_password: ""
  ha_url: "https://ha.collinscreations.co.uk/dashboard-home/0"
  ha_dashboard: ""
  login_delay: 1.0
  zoom_level: 100
  browser_refresh: 600
  screen_timeout: 0
  hdmi_port: 0
  ha_theme: "dark"
  ha_sidebar: "none"

schema:
  ha_username: str
  ha_password: password
  ha_url: str
  ha_dashboard: str?
  login_delay: float(0,)
  zoom_level: int(10,1000)
  browser_refresh: int(0,)
  screen_timeout: int(0,)
  hdmi_port: int(0,1)
  ha_theme: list(auto|dark|light|none)
  ha_sidebar: list(full|narrow|none)

translations:
  - en

environment:
  DISPLAY: ":0"
