---
version: 2.7.4
slug: mariadb
name: MariaDB
description: A SQL database server with Galera clustering support
url: https://github.com/home-assistant/addons/tree/master/mariadb
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
backup_post: unlock-tables-for-backup
backup_pre: lock-tables-for-backup
image: homeassistant/{arch}-addon-mariadb
init: false
options:
  databases:
    - homeassistant
  logins:
    - password: null
      username: homeassistant
  rights:
    - database: homeassistant
      username: homeassistant
  # Galera cluster options
  galera_enabled: false
  cluster_name: "homeassistant_cluster"
  node_name: "node1"
  node_address: ""
  cluster_address: ""
  wsrep_sst_user: "wsrep_sst"
  wsrep_sst_password: ""
ports:
  3306/tcp: 3306
  4567/tcp: 4567
  4568/tcp: 4568
  4444/tcp: 4444
host_network: true
apparmor: false
schema:
  databases:
    - str
  logins:
    - username: str
      password: password
  rights:
    - database: str
      privileges:
        - "list(ALTER|CREATE|CREATE ROUTINE|CREATE TEMPORARY TABLES|\
          CREATE VIEW|DELETE|DELETE HISTORY|DROP|EVENT|GRANT OPTION|INDEX|\
          INSERT|LOCK TABLES|SELECT|SHOW VIEW|TRIGGER|UPDATE)?"
      username: str
  mariadb_server_args:
    - str?
  # Galera cluster options
  galera_enabled: bool?
  cluster_name: str?
  node_name: str?
  node_address: str?
  cluster_address: str?
  wsrep_sst_user: str?
  wsrep_sst_password: password?
services:
  - mysql:provide
startup: system
timeout: 300
