---
name: "MariaDB_Galera"
version: "1.0.0"
slug: "mariadb"
description: "MariaDB server with Galera cluster replication support"
startup: services
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armv7
host_network: true

services:
  - mysql:provide

options:
  databases:
    - homeassistant
  users:
    - username: homeassistant
      password: ""
  rights:
    - username: homeassistant
      database: homeassistant
  logins:
    - username: homeassistant
      password: ""
  # Galera cluster options
  root_password: ""
  replicate_from_ip: "192.168.68.2"
  replicate_user: "replicator"
  replicate_password: ""
  node_name: "haos-node"
  node_address: "192.168.71.215"
  cluster_name: "haos_cluster"

schema:
  databases:
    - str
  users:
    - username: str
      password: str
  rights:
    - username: str
      database: str
  logins:
    - username: str
      password: str
  root_password: "str?"
  replicate_from_ip: "str?"
  replicate_user: "str?"
  replicate_password: "str?"
  node_name: "str?"
  node_address: "str?"
  cluster_name: "str?"
