---
name: Portainer
version: dev
slug: portainer
description: Container Management System from Portainer.io
url: https://github.com/jc21/ha_addons/tree/main/portainer
webui: http://[HOST]:[PORT:9000]
init: false
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 9000
panel_icon: mdi:docker
panel_title: Portainer
ports:
  9000/tcp: 9000
privileged:
  - NET_ADMIN
host_network: false
apparmor: false
docker_api: true
